### PR TITLE
In-tree kernel module replacement

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**
This PR implements in-tree kernel module replacement per user request:
1) Add a boolean flag to KernelMapping and to Container definition
   In case KernelMapping's field is defined, it takes precedence over
   Container field
2) In case the boolean flag is defined, the PostStart command will now
   first try to remove in-tree kernel module, and only after that will try
   to insert the kernel module stored in the container image
3) unit-test

### CODE REVIEW

**Comment by ybettan** [comment]
Last time we talked about it I remember we said we need to check if it is possible to load the in-tree driver back once the module is removed. Do we have more knowledge about it?

**Comment by yevgeny-shnaidman** [comment]
> Last time we talked about it I remember we said we need to check if it is possible to load the in-tree driver back once the module is removed. Do we have more knowledge about it?

This is a very problematic thing to do: we don't know exactly where the in-tree kernel module is stored ( it can be under /lib/modules, but it can also be under a different path). We don't know if there is a modporbe.conf file  for the in-tree kernel module, and it may conflict with the modprobe.conf stored in the containerImage. All in all, it seems like a lot of work, a lot of new definitions, for very-very small benifit, which we aren't even sure if the customer wants

**Comment by ybettan** [comment]
Fixes https://github.com/kubernetes-sigs/kernel-module-management/issues/104.

**Comment by ybettan** [comment]
What happens if the in-tree module we would like to remove have a different name than the one we are inserting?

**Comment by yevgeny-shnaidman** [comment]
> What happens if the in-tree module we would like to remove have a different name than the one we are inserting?

We don't support that option. The main goal of this issue is to allow user to replace the version of an existing driver. The in-tree is usually 2-3 years behind the current driver, so customers just want to replace to a newer version, which means the same driver. We may get back to this option once there is a request for that, but we have not seen such a request yet

**Comment by ybettan** [comment]
SGTM.
I am OK to merge if @qbarrand is.

**Comment by qbarrand** [comment]
What is the downside of making that property a string instead? We would address the use case of different names for free.

**Comment by yevgeny-shnaidman** [comment]
> What is the downside of making that property a string instead? We would address the use case of different names for free.

I don't think we want to support the unloading of different names. 2 reason:
1) we have never seen a user-case for that
2) this option will allow one module to unload the kernel modules of another module (either intentionally or by mistake). It will be a hell to debug. 
I don't think we should go that way, unless we see a number of use-cases for that.

**Pull request merged**
