### PR TITLE
Refactoring ModuleReconciler

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**
This PR add an inner helper interface to the ModuleReconciler. Now the reconcile loop almost entirely uses interface functions in its logic, which allows for shorter and saner unit-tests

### CODE REVIEW

**Comment by qbarrand** [comment]
@yevgeny-shnaidman the PR decreases the unit test coverage.

**Comment by ybettan** [comment]
Looks good to me.
Let's fix the coverage decrease as @qbarrand said.

**Comment by yevgeny-shnaidman** [comment]
> @yevgeny-shnaidman the PR decreases the unit test coverage.

Fixed

**Comment by ybettan** [comment]
Looks like `codecov` isn't creating a new comment but seems like the coverage issue was solved https://app.codecov.io/github/kubernetes-sigs/kernel-module-management/commit/77f544ee1962534776033f01e16fe2e2f0d19212.

/lgtm

**Pull request merged**
