### PR TITLE
Add EXTRA_MODULE variable to kmm-kmod Makefile

### PR DESCRIPTION
**Pull request by enriquebelarte**
Add EXTRA_MODULE variable to Makefile so extra module name

can be set in args.

### CODE REVIEW

**Comment by qbarrand** [comment]
Could this be something more explicit, such as `EXTRA_MODULE`?

**Comment by ybettan** [comment]
Can you please elaborate on the use-case for that change?

**Comment by enriquebelarte** [comment]
> Can you please elaborate on the use-case for that change? Why do we need it? An example on the previous usage VS the new usage can help as well.

It is something that @cvultur thought as something that would help on separating test-cases so name of the "EXTRA" module would not be always a fixed name and could be set as an extra argument during build step, ie:

...  
 `build:`  
 `buildArgs:`  
 `- name: EXTRA_MODULE`  
 `value: multi-stage.o`  
 `dockerfile: |`  
 `FROM gcr.io/myrepo/base:0.1 as builder`  
 `ARG KERNEL_VERSION`  
 `ARG EXTRA_MODULE`

...

If no EXTRA\_MODULE argument is set then behavior is same as before.

**Comment by cdvultur** [comment]
Indeed @enriquebelarte, that is the purpose for this change

/lgtm

**Pull request merged**
