### PR TITLE
Document symlinks for in-tree dependencies

### LINKED ISSUE #517: Docs: add an example of Dockerfile that utilizes link for dependencies on in-tree kmod
By linking a symbolic link `/opt/lib/modules/${kernelVersion}/system` targeting `/lib/modules/${kernelVersion}`, we can have `depmod` use in-tree kmods from the build node when figuring out dependencies.
Because we mount the host's `/lib/modules/${kernelVersion}` into the ModuleLoader pod, this link remains valid when we run modprobe.

This flow should be documented in the docs and a working example should be provided.

Initial issue: https://github.com/intel/intel-data-center-gpu-driver-for-openshift/issues/49
Mentioned at the [2023-07-26 community meeting](https://docs.google.com/document/d/1b-wFATh2A0Pm1P3k11lniSeRP4q74rUa1fTvmk_ZdWY/edit#heading=h.3nujzz6y2g98).

### PR DESCRIPTION
**Pull request by qbarrand**
Fixes #517

@hershpa could you please have a look at this and let me know if this is clear enough? Thanks!

/cc @mresvanis

### CODE REVIEW

**Comment by hershpa** [comment]
> Fixes #517
> 
> @hershpa could you please have a look at this and let me know if this is clear enough? Thanks!
> 
> /cc @mresvanis

@qbarrand, this looks good to me. Thanks!

**Comment by mresvanis** [comment]
@qbarrand do we perhaps need to adjust the [lab](https://github.com/kubernetes-sigs/kernel-module-management/tree/main/docs/mkdocs/lab) manifests as well?

**Comment by mresvanis** [comment]
> @qbarrand do we perhaps need to adjust the [lab](https://github.com/kubernetes-sigs/kernel-module-management/tree/main/docs/mkdocs/lab) manifests as well?

We don't have to update the lab, as there is no kmod depending in an in-tree one :+1:

**Pull request merged**
