### PR TITLE
Fixing `check-commits-count` to work on other branches than `main`.

### PR DESCRIPTION
**Pull request by ybettan**
Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

---

/cc @qbarrand

### CODE REVIEW

**Comment by ybettan** [comment]
/hold
It might not fix the issue

**Comment by mresvanis** [comment]
> /hold
> It might not fix the issue

After researching and internal discussions it seems that this change should work as expected. To sum up, the CI checks out the target branch, merges the PR commits on top of the latter and continues with the respective test.

**Pull request merged**
