### PR TITLE
Bump Kubernetes dependencies

### PR DESCRIPTION
**Pull request by qbarrand**
Combines `client-go`, `kubectl` and `controller-runtime` updates.

/cc @yevgeny-shnaidman @ybettan

### CODE REVIEW

**Comment by ybettan** [comment]
@qbarrand We should probably close those PRs (or they will close automatically?) once this one is merged.
* https://github.com/kubernetes-sigs/kernel-module-management/pull/216/files
* https://github.com/kubernetes-sigs/kernel-module-management/pull/201/files
* https://github.com/kubernetes-sigs/kernel-module-management/pull/199/files
* https://github.com/kubernetes-sigs/kernel-module-management/pull/197/files

**Comment by qbarrand** [comment]
> or they will close automatically?

They will. I think we're waiting on a minikube release compatible with kube 1.26 for e2e tests to pass on that one.

**Pull request merged**
